version: '3'

services:
  mysql:
    build: .
    container_name: casa_brasilis_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12516692
      MYSQL_DATABASE: casa_brasilis_db
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql