version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["yarn", "dev"]
    # depends_on:
    #   - db
    networks:
      - my_network

  # db:
  #   image: postgres:11
  #   container_name: postgres_db
  #   ports:
  #     - "5432:5432"
  #   env_file:
  #   - .env
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - my_network

networks:
  my_network:
