-- AlterTable
ALTER TABLE "properties" ALTER COLUMN "zipcode" SET DATA TYPE TEXT,
ALTER COLUMN "interest_rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "rental_price" SET DATA TYPE DOUBLE PRECISION;
